#Esse projeto visa criar assuntos e piadas de forma automatica 
import random

def piadas_engraçadas(piadas):
    piadas=["Por que o esqueleto não brigou com ninguém?\nPorque ele não tem estômago para isso!",
            "O que é um pontinho amarelo no alto de uma montanha?\nUm girassol perdido!",
            "Por que o livro de matemática está sempre nervoso?\nPorque tem muitos problemas.",
            "Qual é o animal mais antigo?\nA zebra, porque está em preto e branco!",
            "O que um pato falou para a pata?\nVem quá!",
            "Por que os fantasmas são péssimos para contar mentiras?Porque são transparentes",
            "Por que a plantinha não foi atendida no hospital?Porque só tinha médico de plantão.",
            "O que a Lua disse ao Sol? Nossa, você é tão grande e ainda não te deixam sair à noite!",
            "Você sabe por que a água foi presa?Porque ela matou a sede.",
            "Qual a cidade brasileira que não tem táxi?Uberlândia.",
            "Um eletricista vai até a UTI de um hospital, olha para os pacientes ligados a diversos tipos de aparelhos e diz-lhes: Respirem fundo: vou trocar o fusível.",
            "Qual a fórmula da água benta?H Deus O.",
            "Miguel, aonde vai tão circunspecto e assaz atribulado?Eu ia no banheiro, mas agora vou consultar um dicionário.",
            "Qual o contrário de papelada?Pá vestida.",
            "Contei uma piada química... não teve reação.",
            "Um canguru consegue pular mais alto que o Banespão?Claro, o Banespão não pula.",
            "O que o tijolo falou para o outro?Há um ciumento entre nós.",
            "O que o cadarço falou para o tênis?Eu me amarro em você.",
            "Por que o jacaré tirou o filho da escola?Porque ele réptil de ano.",
            "Como o Batman conheceu o Robin?Pelo bat-papo.",
            "Você sabe quem é o rei dos queijos?É o reiqueijão.",
            "Por que o porco está sempre feliz?Porque está de bacon a vida.",
            "Qual a diferença entre o gato e coca-cola? O gato mia e a coca light.",
            "Qual é o cúmulo da solidão?Morar sozinho e fugir de casa.",
            "Qual é o alimento mais sagrado que existe?O amém doim.",
            "Por que a mulher do Hulk divorciou-se dele?Porque ela queria um homem mais maduro…",
            "Você conhece a piada do fotógrafo? Ainda não foi revelada.",
            "Então, o que o pagodeiro foi fazer na igreja?Foi cantar Pá God.",
            "O que o cliente disse ao entrar na H.Stern?E aí, tudo joia?"
            "Por que o rato entrou na igreja?\nPorque viu o gato a rezar!",
            "Qual a fórmula da água benta?\nH Deus O.",
            "Qual a fórmula da água benta?\nH Deus O.",
            "Na frase 'ele acordou cedo', onde está o sujeito?\nEm algum lugar com sono.",
            "Quer pedir desculpas?\nA partir de hoje só aceito pedido em dinheiro.",
            "Gosto tanto de vencer que nem peso eu perco.",
            "Um homem vai a uma loja para comprar um novo celular.\nModelo? - pergunta o atendente.\nNão, eu sou mecânico, mas obrigado!",
            "Já marquei na agenda quando vou resolver todos os meus problemas: no próximo 30 de fevereiro.",
            "Então, o que o pagodeiro foi fazer na igreja?\nFoi cantar Pá God.",
            "O que o cliente disse ao entrar na H.Stern?\nE aí, tudo joia?",
            "Por que o rádio não pode ter filhos?\nPorque ele é stereo.",
            "Por que o policial não usa sabão?\nPorque ele prefere deter gente.",
            "Na frase 'Proibido estacionar', qual é o sujeito da oração?\nSujeito a guincho.",
            "O que a galinha foi fazer na igreja?\nAssistir a Missa do Galo.",
            "O que o padeiro falou para o John Lennon?\nO sonho acabou.",
            "Querido, onde está aquele livro 'Como viver 100 anos?'\n- Joguei fora!\n- Jogou fora? Por quê?\n- É que sua mãe vem nos visitar amanhã e eu não quero que ela leia essas coisas!",
            "Afinal, você conhece a piada do pônei?\n- Pô nei eu.",
            "Por que as plantas pequenas não falam?\nPorque elas são mudinhas.",
            "Então, por que a velhinha não usa relógio?\nPorque ela é sem hora.",
            "O que é um pontinho azul no gramado?\nResposta: é uma formiguinha de calça jeans.",
            "O que é um pontinho preto no avião?\nResposta: Aeromosca",
            "Qual é o fim da picada?\nQuando o mosquito vai embora.",
            "Por que os bombeiros não conseguem andar?\nPorque eles só-correm.",
            "Qual o animal que já valeu muito, mas que atualmente não vale nada?\nO javali.",
            "Como deixar alguém curioso? Eu conto amanhã.",
            "Por que os fantasmas são péssimos para contar mentiras? Porque são transparentes.",
            "Por que a plantinha não foi atendida no hospital? Porque só tinha médico de plantão.",
            "Se você está se sentindo sozinho, abandonado, achando que ninguém liga para você... Atrase um pagamento.",
            "- Doutor, como eu faço para emagrecer?\n- Basta a senhora mover a cabeça da esquerda para a direita e da direita para a esquerda.\n- Quantas vezes, doutor?\n- Todas as vezes que lhe oferecerem comida.",
            "Dois amigos se encontram depois de muitos anos.\n- Casei, separei e já fizemos a partilha dos bens.\n- E as crianças?\n- O juiz decidiu que ficariam com aquele que mais bens recebeu.\n- Então ficaram com a mãe?\n- Não, ficaram com nosso advogado.",
            "O que a Lua disse ao Sol? – Nossa, você é tão grande e ainda não te deixam sair à noite!",
            "Eu perdi peso no mês passado. Mas este mês ele já me encontrou de novo.",
            "Sabe qual é a melhor forma de consumir o tempo? Comer relógios.",
            "Eu saí do meu trabalho. Não conseguiria continuar lá depois do que o meu chefe disse...\nO que ele disse?\nVocê está despedido.",
            "- Dói, né?\n- O quê?\n- Deitar no sofá e lembrar que esqueceu o controle.",
            "Dois tomatinhos iam atravessar a rua, e um disse ao outro:\n-Cuidado, vem aí um carro!\nO outro não ouviu nada e atravessou. O carro passou por cima dele e o outro disse:\n– Já não é um tomate, é ketchup!",
            "O condenado à morte esperava a hora da execução, quando chegou o padre:\n- Meu filho, vim trazer a palavra de Deus para você.\n- Perda de tempo, seu padre. Daqui a pouco vou falar com Ele, pessoalmente. Algum recado?",
            "Um rapaz chegou num velório e a primeira coisa que perguntou foi:\n- Qual é a senha do Wi-Fi?\nUm parente incomodado disse:\n– Respeite o falecido!\nE ele perguntou:\n– É tudo junto?",
            "Manuel está tomando banho, e grita para Maria:\n– Ô Maria, me traz um xampu.\nE Maria lhe entrega o xampu. Logo em seguida, ele grita novamente:\n– Ô Maria, me traz outro xampu.\n– Mas eu já te dei um agorinha mesmo, homem!\n– É que aqui está dizendo que é para cabelos secos, e eu já molhei os meus.",
            "Você sabe por que a água foi presa?\n- Porque ela matou a sede.",
            "Aluno de Direito ao fazer prova oral:\n- O que é uma fraude?\n- É o que o senhor professor está fazendo - responde o aluno.\nO professor fica indignado: ora essa, explique-se.\nEntão diz o aluno: segundo o Código Penal, comete fraude todo aquele que se aproveita da ignorância do outro para o prejudicar.",
            "Um eletricista vai até a UTI de um hospital, olha para os pacientes ligados a diversos tipos de aparelhos e diz-lhes:\nRespirem fundo: vou trocar o fusível.",
            "Fui no café e perguntei se o salgado era de hoje.\n– Não, é de ontem.\n– E como faço pra comer o de hoje?\n– Volte amanhã!",
            "Querido, onde está aquele livro 'Como viver 100 anos?'\n- Joguei fora!\n- Jogou fora? Por quê?\n- É que sua mãe vem nos visitar amanhã e eu não quero que ela leia essas coisas!",
            "Afinal, você conhece a piada do pônei?\n- Pô nei eu.",
            "O pai pergunta à filha:\n- Filha, você acha que sua professora desconfia que eu estou te ajudando a fazer a lição de casa?\n- Acho que sim, pai. Ela até já me disse que você deveria voltar para escola!",
            "Qual o animal que já valeu muito, mas que atualmente não vale nada?\n- O javali."
            ]
    resultado=random.choice(piadas)
    return resultado
    
def charadas_engraçadas(charadas):
    charadas=["Sem sair do seu cantinho, é capaz de viajar ao redor do mundo.\nResposta: o selo","É feito de água, mas se for colocado dentro da água morrerá.\nResposta: o gelo",
        "É alta quando jovem e baixinha quando fica velha. Além disso, é rápida quando é magra e lenta quando é gorda.\nResposta: a vela",
        "Pode ser atirado do alto de um prédio e ficar super bem. Mas quando é colocado na água morre pouco tempo depois.\nResposta: o papel",
        "Fica cada vez mais molhado quanto mais a gente seca.\nResposta: a toalha",
        "Anda sobre quatro membros de manhã, dois à tarde e três à noite.\nResposta: o ser humano",
        "Você tira a minha pele. Eu não choro. Você, sim.\nResposta: a cebola",
        "Você pode pegar, mas não pode jogar.\nResposta: resfriado",
        "É mais leve que uma pluma, mas nem o homem mais forte do mundo pode segurá-la por mais de um minuto.\nResposta: a respiração",
        "Ocorre uma vez a cada minuto, duas vezes a cada momento, mas jamais a cada quinhentos anos.\nResposta: a letra 'm'",
        "Dois pais e dois filhos saíram para pescar. No final do dia, eles haviam pescado três peixes. Um dos pais disse: 'Isso é o suficiente. Temos um peixe para cada um de nós'. Como isso é possível?\nResposta: era um pai, um filho e um filho do filho (neto do primeiro pai)",
        "Sobe, sobe, sobe e jamais desce.\nResposta: a idade",
        "Se você olhar para o meu rosto, não encontrará treze em nenhum lugar. Quem eu sou?\nResposta: o relógio",
        "Está sempre a caminho, mas nunca chega.\nResposta: amanhã",
        "Tem cidades, mas não tem casas. Tem montanhas, mas não tem árvores. Tem água, mas não tem peixe.\nResposta: o mapa",
        "Pertence a você, mas as outras pessoas usam mais do que você.\nResposta: seu nome",
        "A família Silva: O senhor e a senhora Silva têm 6 filhas. Cada filha tem um irmão. Quantas pessoas fazem parte da família Silva?\nResposta: 9 pessoas",
        "Não é vivo, mas cresce. Não tem pulmões, mas precisa de ar. Não tem boca, mas a água pode matá-lo.\nResposta: o fogo",
        "É mais útil quando é quebrado.\nResposta: o ovo",
        "É preto quando você o compra, vermelho quando você o usa e cinza quando você o joga fora.\nResposta: carvão",
        "Tem 6 faces, mas não usa maquiagem. Tem também 21 olhos, mas não pode ver.\nResposta: dado",
        "Faz duas pessoas a partir de uma só.\nResposta: espelho",
        "Você me tem hoje e amanhã você me terá ainda mais. Conforme o tempo passa, eu não sou nada fácil de guardar. Não ocupo nenhum espaço, mas estou sempre num único lugar. Eu sou o que você viu, não o que você vê.\nResposta: memória",
        "Elas não têm carne, penas, escamas ou ossos. Mas têm dedos próprios.\nResposta: luvas",
        "Sempre estou dentro de você, às vezes em cima. Se eu cercar você completamente, posso te matar.\nResposta: água",
        "Quanto mais você tira, maior eu fico.\nResposta: buraco",
        "É cheio de furinhos, mas ainda assim consegue segurar a água.\nResposta: esponja",
        "As casas: Havia uma grande casa verde. Dentro dela, havia uma casa branca. Dentro da casa branca, uma casa vermelha. E dentro da casa vermelha um monte de bebezinhos. Quem eu era?\nResposta: uma melancia",
        "Não tem pés, mãos ou asas, mas pode subir aos céus.\nResposta: fumaça",
        "Não é roupa, mas pode cobrir seu corpo. Quanto mais é usado, mais fino fica.\nResposta: sabão",
        "A que pergunta para a qual você nunca responderá 'sim'?\nResposta: 'Você já está dormindo?'",
        "Está sempre na sua frente, mas não pode ser visto?\nResposta: o futuro",
        "Quanto mais disso há, menos você vê.\nResposta: escuridão",
        "Jogamos fora quando estamos em necessidade e tomamos de volta quando não precisamos?\nResposta: a âncora",
        "Uma planta que não enxerga?\nResposta: acelga",
        "Quanto mais limpo, mais sujo está?\nResposta: o pano de chão",
        "Está no início da rua, no final do lar e no meio da cara?\nResposta: a letra 'r'",
        "Acontece quando um leão senta na pata?\nResposta: o pato fica viúvo",
        "Possui inúmeras rodas, mas nunca sai do lugar?\nResposta: um estacionamento",
        "Duas coisas que você não pode comer no café da manhã?\nResposta: o almoço e o jantar",
        "Pode ser quebrado, mas nunca segurado?\nResposta: uma promessa",
        "Quando você tem, jamais partilha. Quando partilha, perde imediatamente?\nResposta: um segredo",
        "Não pode ser comprado, mas pode ser roubado. Não tem valor para uma pessoa sozinha, mas é inestimável para duas.\nResposta: o amor",
        # Charadas engraçadas
        "Quantas espécies Moisés levou com ele na Arca?\nResposta: nenhuma. Quem construiu a arca foi Noé, não Moisés.",
        "Imagine que você está numa sala bem escura. Como você sai de lá?\nResposta: é só deixar de imaginar.",
        "Qual invenção permite que se olhe através da parede?\nResposta: a janela",
        "O que tem no final do arco-íris?\nResposta: a letra 's'",
        "Um cavaleiro saiu da cidade no Sábado e passou a noite numa pousada na cidade vizinha. No dia seguinte, ele voltou à cidade no Sábado. Como isso é possível?\nResposta: seu cavalo se chama Sábado",
        "Jaime saiu para caminhar quando começou a chover. Ele não tinha guarda-chuva nem usava chapéu.\nResposta: Jaime é careca",
        "Antes do Monte Everest ser descoberto, qual era a maior montanha da Terra?\nResposta: o Monte Everest",
        "Um motorista de ônibus estava descendo uma rua na cidade de São Paulo. No primeiro cruzamento, não parou no sinal vermelho e virou à esquerda na contramão. Um pouco mais adiante, deu de frente com uma viatura da polícia de trânsito. Mas, apesar disso, os policiais o deixaram passar. Como isso é possível?\nResposta: ele estava caminhando, não dirigindo",
        "Quando dá azar ver um gato preto?\nResposta: quando você é um rato",
        "Por que o zagueiro, quando se aposenta, é o jogador que deixa mais saudades?\nResposta: porque o zagueiro é o que faz mais falta",
        "Por que o dinossauro não consegue bater palma?\nResposta: porque ele já foi extinto",
        "Eu estava escovando os dentes e a tampinha da pasta caiu no ralo. O que saiu do chuveiro quando eu fui tomar banho?\nResposta: água",
        "Qual a parte do corpo que mais coça?\nResposta: a unha",
        "Como chama o policial que se olhou no espelho?\nResposta: policial civil",
        "Por que pintores e costureiras às vezes não vão para o céu quando morrem?\nResposta: porque eles pintam e bordam a vida inteira",
        "Por que a mulher usava capacete na mesa de jantar?\nResposta: Por causa de sua dieta radical",
        "Qual é a melhor cura para a caspa?\nResposta: a calvície",
        "Qual palavra no dicionário está escrita incorretamente?\nResposta: Incorretamente",
        # Charadas difíceis
        "Um homem foi encontrado morto dentro de uma cabana. Na sua mão direita, é encontrada uma arma. Na sua mão esquerda, um gravador. Na gravação, o homem fala da vida horrível que levava e do modo como quis dar um fim nela. A gravação acaba com um barulho de tiro. A polícia está prestes a concluir o caso como suicídio até que você, um dos investigadores, chama a atenção para uma prova que põe em dúvida a tese de que o homem se matou. Qual é essa prova?\nResposta: se a gravação termina com um tiro, como o homem teria sido capaz de desligar o gravador depois disso?",
        "Quando você me vira de lado, sou tudo. Quando me corta ao meio, não sou nada.\nResposta: o número 8",
        "Eu tenho chaves, mas não tenho fechaduras. Eu tenho espaço, mas não tenho espaço. Você pode entrar, mas não pode sair. O que eu sou?\nResposta: um teclado"
    ]
    resultado=random.choice(charadas)
    return resultado    
    
def assuntos_gerador(assuntos):
    assuntos=[
            "Como você acha que o seu melhor amigo te descreveria?",
    "O que aconteceu de interessante no seu dia?",
    "Você tem algum pet? Como se chama?",
    "Qual foi o vídeo mais engraçado que você viu nos últimos dias?",
    "Se você pudesse ter um super poder, qual seria?",
    "Você tem algum talento que a maior parte das pessoas não sabe?",
    "Se você pudesse viajar no tempo, iria para que época?",
    "Se você pudesse conhecer qualquer figura histórica, quem seria?",
    "Em quê você trabalha? Ou o que estuda?",
    "Me conta uma coisa que todo mundo gosta e você não?",
    "Você prefere fotografar ou ser fotografado?",
    "Você se considera uma pessoa tímida ou extrovertida?",
    "O que você acha que todo mundo deveria saber?",
    "Você prefere aproveitar a manhã ou a noite?",
    "Como você descreveria o seu grupo de amigos mais próximos?",
    "Qual é a sua comida preferida?",
    "Você prefere balada ou barzinho?",
    "Prefere verão ou inverno?",
    "Se pudesse morar em qualquer lugar do mundo, onde seria?",
    "Você gosta de futebol? Torce para que time?",
    "Qual é a sua cor preferida?",
    "Você prefere praia ou campo?",
    "Com que animal você mais se identifica?",
    "Você tem algum número da sorte? Qual é?",
    "Qual foi o lugar mais bonito que visitou?",
    "Como é um dia perfeito para você?",
    "Que restaurante você me recomendaria?",
    "Qual é a sua viagem dos sonhos?",
    "Que música tem tudo a ver com você?",
    "Tem feito maratona de séries? Quais?",
    "Que filme você considera inesquecível?",
    "Que livro você me recomendaria?",
    "Quem é o seu artista favorito?",
    "Que tipo de música você escuta?",
    "Qual foi o melhor show que você assistiu até hoje?",
    "Qual foi a última música que você ficou cantando durante dias?",
    "Que música você costuma escutar para ficar de bom humor?",
    "Qual filme marcou a sua infância?",
    "O que você faz nos tempos livres?",
    "Você pratica alguma atividade física?",
    "Você toca algum instrumento?",
    "Você gosta de dançar?",
    "Você curte videogames? Quais?",
    "Você usa redes sociais? Quais?",
    "O que ajuda você a relaxar e a manter o equilíbrio?",
    "Onde você cresceu?",
    "Que profissão você queria ter quando era criança?",
    "Qual era o seu desenho preferido na infância?",
    "Que sonho você já realizou?",
    "Que sonho você quer realizar?",
    "Qual foi a coisa mais engraçada que já aconteceu com você?",
    "Quais são os seus objetivos para os próximos anos?",
    "Existe alguma coisa que você realizou e sentiu muito orgulho?",
    "Qual é o medo mais bobo que você tem?",
    "O que você mais admira nos outros?",
    "Você tem algum lema de vida?",
    "Qual foi a maior lição que você aprendeu até hoje?",
    "Qual foi o acontecimento mais marcante da sua vida?",
    "Qual é a sua maior qualidade? E o seu maior defeito?",
    "Quem são as pessoas que mais te inspiram? Por quê?",
    "Me conta um tema que tem estado na sua cabeça ultimamente?",
    "O que deixa você muito feliz?",
    "O que mais enche você de orgulho?",
    "Do que você sente saudades? Ou de quem?",
    "Qual foi o melhor período da sua vida?",
    "Como seria um dia perfeito para você?",
    "Como você nos imagina em 10 anos?",
    "É melhor fazer planos a longo prazo juntos ou viver no presente sem pensar muito no futuro?",
    "Qual é a lembrança que você tem de quando a gente se viu pela primeira vez?",
    "Você já pensou em terminar? Se sim, por qual motivo?",
    "Você mudaria alguma coisa em mim?",
    "Qual a lembrança mais feliz que te vem à mente quando pensa em mim?",
    "O que achou de mim quando me viu pela primeira vez?",
    "O que você mais gosta em mim?",
    "O que é mais importante: ter amigos em comum ou cada um ter o seu grupo?",
    "O que mais te acalma?",
    "Se pudesse voltar no tempo, mudaria alguma coisa no nosso relacionamento?",
    "É melhor ter independência financeira ou compartilhar todas as finanças?",
    "Existe alguma coisa que eu já fiz e que te deixou muito alegre?",
    "Que estilo de música seria a trilha sonora do nosso relacionamento? Pop, rock, blues, reggae, sertanejo…?",
    "Qual o maior segredo para manter viva a paixão num relacionamento?",
    "É mais importante ser honesto sempre ou ter cuidado com as palavras para evitar magoar?",
    "Qual a sua linguagem do amor preferida? Palavras de afirmação, tempo de qualidade, dar presentes, atos de serviço ou toque físico?",
    "O que você mais valoriza em uma pessoa?",
    "Qual a sua maior insegurança?",
    "O que você levaria para uma ilha deserta?",
    "Qual o seu maior medo?",
    "Qual o seu maior sonho?",
    "Já sofreu por amor?",
    "O que mudaria do seu passado?",
    "Qual o momento mais difícil que você passou na vida?",
    "Qual foi a sua maior desilusão amorosa?",
    "Qual era o seu desenho favorito quando criança?",
    "Qual é a coisa mais louca que já fez por amor?",
    "Quem é a pessoa que mais influenciou a sua vida?",
    "O que você sempre quis fazer, mas nunca teve coragem?",
    "Qual o seu maior defeito?",
    "Do que você sente mais vergonha na vida?",
    "Você já mentiu para mim?",
    "Se a sua família se opusesse sobre a nossa relação, o que você faria?",
    "Neste tempo que estamos juntos, você chegou a se interessar por outra pessoa?",
    "Você acredita em alma gêmea?",
    "Você acredita em destino?",
    "O que você estaria disposto a fazer por 1 milhão de reais?",
    "Quem foi a primeira pessoa que você beijou?",
    "Se você pudesse mudar de vida com alguém, quem seria?",
    "Você ficaria sem escutar música ou sem assistir filmes por um mês?",
    "O que você diria para mim se tivesse me conhecido quando criança?",
    "Três coisas que você gostaria de fazer antes de morrer?",
    "Se dinheiro não fosse um empecilho, o que você faria com o seu tempo?",
    "Existe alguma coisa que você fez quando era pequeno e que seus pais nunca descobriram?",
    "O que eu poderia fazer para que você se sinta mais amado ou amada?",
    "Qual a lembrança de nós dois que você guarda com mais carinho?",
    "Você acha que passamos tempo suficiente juntos?",
    "De todos os outros casais que conhecemos, qual você acha que tem a melhor relação?",
    "Gostaria de ter quantos filhos no total?",
    "Quem foi o seu primeiro crush e como ele (ou ela) era?",
    "Como foi a sua primeira decepção amorosa?",
    "Qual a maior lição da sua maior decepção amorosa?",
    "Qual o seu trabalho dos sonhos quando você era criança?",
    "Você acha que é mais importante ser inteligente ou ser gentil?",
    "Sua família tem alguma tradição?",
    "Quem você acha que é mais ciumento entre nós dois?",
    "O que mais te atrai em mim?",
    "Como você expressa a sua raiva?",
    "Você preferiria ser um cantor muito talentoso ou um dançarino muito talentoso?",
    "Você acredita em 'sorte' ou acha que somos nós que criamos as melhores oportunidades?",
    "Você costuma lembrar dos seus sonhos quando acorda?",
    "Quem você acha que sobreviveria a um apocalipse? Eu ou você?",
    "Você preferiria ser um vampiro ou um lobisomem por um dia?",
    "Qual casal de celebridades você mais admira?",
    "Você se considera mais otimista ou pessimista?",
    "Você acredita que tudo acontece por uma razão?",
    "Qual canção descreveria o nosso amor?",
    "Tem alguma música que faz você lembrar de mim?",
    "Se pudesse ser um animal em outra vida, qual seria?",
    "Quantas vezes você já se apaixonou?",
    "Você acredita que algumas mentiras são justificáveis?",
    "Você prefere tempos mais quentes ou mais frios?",
    "Onde você se sente mais confortável com você mesmo?",
    "Qual instrumento musical você sempre quis aprender a tocar?",
    "Qual o melhor elogio que você já recebeu?",
    "Um país você gostaria de explorar intensamente.",
    "O que traz maior significado para a sua vida?",
    "Quais são os pequenos prazeres da vida que mais te agradam?",
    "Qual a maior burrada que você já fez na vida?",
    "Qual a mudança mais significativa que você gostaria de fazer na sua vida?",
    "Qual a lição mais difícil que você aprendeu ao longo da vida?",
    "Tem vergonha de algo que você já fez?",
    "Se você tivesse 1 milhão de reais para doar para caridade, qual instituição você doaria?",
    "Quando foi a última vez que você chorou?",
    "Qual o maior arrependimento da sua vida?",
    "O que te deixa mais sentimental?",
    "O que te deixa mais estressado com facilidade?",
    "Quais são as palavras que mais te descrevem?",
    "Quais foram os acontecimentos mais importantes da sua vida até agora?",
    "O que te traz mais alegria durante o dia?",
    "Quais hobbies ou atividades você gostaria que a gente começasse como casal?",
    "O que você acha que é a nossa melhor qualidade enquanto casal?",
    "O que poderíamos fazer para deixar a nossa relação mais forte?",
    "O que faz da nossa relação melhor do que outras que você já teve?",
    "Qual a atividade que nós fazemos juntos que te deixa mais feliz?",
    "Qual o presente que eu te dei que te deixou mais feliz?",
    "Em quais novas aventuras você gostaria de embarcar comigo?",
    "Qual o conselho amoroso mais valioso que você já recebeu?",
    "Existe alguma coisa que se eu fizesse você nunca conseguiria perdoar?",
    "Qual comida te faz lembrar de mim?",
    "Você se acha mais parecido com o seu pai ou com a sua mãe?",
    "Você prefere ser beijado ou abraçado?",
    "O que você acha dos relacionamentos abertos?",
    "Qual local você se sente mais seguro?",
    "O que você aprendeu sobre casamento com os seus pais?",
    "Qual era o seu filme preferido quando era criança?",
    "Qual a festa mais divertida que você já esteve?",
    "O que você preferiria ter: uma casa de praia, um barco ou um ano de férias?",
    "Qual foi o seu primeiro crush?",
    "Se pudesse voltar no tempo, que idade gostaria de reviver?",
    "Se pudesse ver o futuro, o que gostaria de saber?",
    "Você costuma se comparar com outras pessoas?",
    "Você chegou a se rebelar na adolescência?",
    "Quais os maiores objetivos que você tem para a nossa relação?",
    "Como você descreveria a nossa química enquanto casal?",
    "Se você tivesse apenas um dia para viver, o que faria?",
    "Qual sonho mais louco que você já teve?",
    "Qual a sua memória favorita de nós dois?",
    "Qual dos nossos amigos em comum você acha mais engraçado?",
    "O que você acha que me difere das outras pessoas?",
    "Qual a pessoa que você mais respeita na vida?",
    "Quais tarefas domésticas você mais detesta fazer?",
    "Você preferiria ser rico ou famoso?",
    "Se tivesse a opção, você viveria para sempre?",
    "Qual a sua maior prioridade na vida hoje?",
    "Qual hábito você mais detesta em outras pessoas?",
    "Qual cidade, país ou local que você mais gostaria que conhecêssemos juntos?",
    "Como você se imagina aposentado?",
    "Quando você soube que realmente gostava de mim?",
    "Quais atores interpretariam a nossa história de vida em um filme?",
    "Se você pudesse trabalhar para uma empresa que admira, qual seria?",
        "Há alguma coisa em você que gostaria de mudar?",
    "Qual a coisa mais simples que te deixa muito feliz?",
    "Você viveria algum dia do nosso namoro em câmera lenta?",
    "Como você se imagina daqui a cinco anos, e como vê nossa relação nesse futuro?",
    "Eu te inspirei a fazer algo de diferente na sua vida?",
    "Qual é a palavra que melhor te define?",
    "E qual é a palavra que melhor me define?",
    "Do que você mais tem medo?",
    "Qual é a minha roupa que você acha que fica melhor em mim?",
    "Qual é a primeira lembrança que você tem da época que era uma criança?",
    "Como você me descreve para os seus amigos?",
    "Por que você se interessou por mim quando nos conhecemos?",
    "O que te faz se sentir amado?",
    "Quais são os seus maiores interesses e paixões?",
    "O que você aprendeu nos seus relacionamentos passados?",
    "O que eu faço que mais te irrita?",
    "Você teria feito de diferente no nosso relacionamento?",
    "Qual foi a última coisa que te provocou mais emoção?",
    "Existe algum conselho que você gostaria de ter dado ao seu eu mais jovem?",
    "Quais são as suas qualidades que você espera que os seus filhos tenham?",
    "E quais são os defeitos que você tem, mas espera que os seus filhos não tenham?",
    "Qual é o propósito ou objetivo que mais te motiva na vida?",
    "Qual seria a sua maior realização pessoal?",
    "O que você mais gosta de fazer quando está comigo?",
    "Você sente saudades de algo que paramos de fazer?",
    "Quando você soube que estava apaixonado por mim?",
    "Qual é o próximo sonho que você gostaria de realizar?",
    "Qual foi a coisa mais estranha que você já fez?",
    "O que você jamais deixaria de comer?",
    "Como seria um dia perfeito na sua vida?",
    "Qual a coisa mais importante que você tem no seu quarto?",
    "Do que você mais gosta em mim?",
    "Qual foi o seu apelido mais estranho?",
    "Qual foi o filme que mais marcou a sua vida?",
    "Qual foi a melhor série que já vimos juntos?",
    "Como você imagina que vai viver a aposentadoria?",
    "Há alguma coisa que você demorou para descobrir sobre mim?",
    "Você prefere gastar o dinheiro em viagens ou em coisas para a casa?",
    "Você já pensou em viver em outro país? Qual?",
    "Você sentia frio na barriga quando me conheceu?",
    "Quando me conheceu, você achou que iríamos namorar?",
    "Tem alguma coisa estranha sobre você que nunca tenha me contado?",
    "Você acredita em almas gêmeas?",
    "O que você sente quando nos abraçamos?",
    "Você gosta de ser surpreendido?",
    "Quando nos beijamos pela primeira vez?",
    "Você gosta do jeito que os seus pais te educaram? Por quê?",
    "O que você amaria fazer comigo?",
    "O que te dá mais esperança?",
    "Você já se arrependeu de algo que fez no nosso namoro?",
    "Você lembra a roupa que eu estava usando quando nos conhecemos?",
    "Quando nos conhecemos, teve alguma coisa que você fingiu gostar para me alegrar?",
    "Se pudéssemos ter nos conhecido em outro momento da vida, em qual você gostaria que tivesse sido?",
    "Qual foi o filme que você mais gostou de assistir comigo?",
    "Você quer ter animais de estimação no futuro? Quantos?",
    "Como e onde seriam as nossas férias dos sonhos?",
    "O que você mais gosta em você?",
    "O que você mais gosta em você quando está comigo?",
    "O que significa companheirismo para você?",
    "Como você gosta de passar os fins de semana?",
    "O que significa ser feliz para você?",
    "Qual a diferença entre paixão e amor?",
    "O que o amor te faz sentir? Descreve o que você sente!",
    "Qual é a palavra que melhor define o nosso namoro?",
    "No que você nos acha mais parecidos?",
    "Como seria um jantar romântico perfeito para você?",
    "Quando eu cozinho alguma comida que ficou ruim, você me conta?",
    "Como você acha que é visto pelas pessoas?",
    "No que você nos acha mais diferentes?",
    "Quantas vezes ao dia você pensa em mim?",
    "Qual é a música que mais simboliza com o nosso namoro?",
    "Como você prefere passar os seus aniversários?",
    "O que podemos fazer para tornar nosso namoro ainda melhor?",
    "Qual hobby novo você gostaria de começar?",
    "Há algum lugar estranho que você sente cócegas?",
    "Qual de nós perde mais tempo no celular?",
    "Qual foi a maior decepção que você já teve?",
    "Qual prato de comida da infância que mais te dá saudades?",
    "Qual foi o presente que você mais gostou de ganhar?",
    "Você já foi traído?",
    "O que você adora fazer em dias de chuva?",
    "O que você adora fazer em dias de sol?",
    "Qual é a sua roupa predileta?",
    "Prefere festa de casamento ou gastar dinheiro numa viagem?",
    "Se pudesse prever a nossa vida daqui 20 anos, como seria?",
    "Você prefere passar as férias na praia, numa nova cidade ou no campo?",
    "Qual foi a coisa mais corajosa que você já fez?",
    "Como você me descreve para a sua família?",
    "De que momento você mais sente saudades da infância?",
    "Onde você adoraria morar?",
    "Você já quebrou algum osso do corpo? Qual?",
    "Até agora, qual foi o melhor ano da sua vida?",
    "Você tem medo de altura? E de insetos?",
    "Qual é o seu trabalho dos sonhos?",
    "Já quebraram o seu coração no passado?",
    "Qual é a minha principal mania?",
    "Qual é o meu filme predileto?",
    "Você tem algum talento escondido?",
    "O que pode acalmar o seu dia?",
    "Qual aplicativo você mais usa no celular?",
    "Você gosta de colecionar alguma coisa?",
    "Qual foi a primeira vez que nos abraçamos?",
    "Quem teve maior iniciativa no início do relacionamento?",
    "O que eu faço que você acha mais engraçado?",
    "Qual foi a primeira vez que saímos para jantar?",
    "O que faz você se apaixonar por alguém?",
    "O que você não perdoaria em um relacionamento?",
    "Para conhecer alguém, qual a pergunta que você sempre faz em um primeiro encontro?",
    "Qual a primeira coisa que você notou em mim?",
    "Qual a parte do corpo que mais admira em outra pessoa?",
    "O que você mais espera de alguém em um relacionamento?",
    "Você acredita em amor à primeira vista?",
    "Para você, o que um relacionamento saudável precisa ter?",
    "O que te faz confiar em alguém?",
    "E o que te faz perder a confiança em alguém?",
    "Como seria a demonstração de amor mais perfeita para você?",
    "Quando você acha que é o melhor momento para duas pessoas começarem a morar juntas?",
    "O que você renunciaria na sua vida para viver um grande amor?",
    "Você acredita em alma gêmea?",
    "O que você considera mais atraente em você?",
    "Você tem alguma mania?",
    "Você conseguiria definir o amor em uma única palavra?",
    "Você é do tipo que dorme brigado ou faz as pazes antes de dormir?",
    "O que você considera ser um amor verdadeiro?",
    "Existe um casal que você admira? Qual e por quê?",
    "O que consegue te deixar curioso sobre a vida de alguém?",
    "O que você nunca faria por amor?",
    "Se hoje fosse o nosso último dia na Terra, o que você gostaria de fazer?",
    "Qual seria a viagem dos seus sonhos a dois?",
    "Como você descreveria o relacionamento perfeito?",
    "Existe alguma coisa que você gostaria de saber sobre mim?",
    "Você beija no primeiro encontro ou prefere conhecer a pessoa melhor?",
    "Você consegue se apaixonar fácil ou se considera uma pessoa difícil de se envolver?",
    "Você já disse “eu te amo” e arrependeu?",
    "Qual é o seu lugar preferido em todo o mundo?",
    "O que você gosta de fazer quando está de folga?",
    "Qual o livro que mais te marcou?",
    "Você tem algum apelido de infância?",
    "Prefere comidas doces ou salgadas?",
    "Se você tivesse que escolher um lugar para viver pelo resto da sua vida, onde seria e por quê?",
    "Se você pudesse escolher uma habilidade para aprender em apenas um dia, qual seria?",
    "Qual o seu maior sonho?",
    "Qual é o filme que mais te fez chorar e por quê?",
    "Qual o tipo de música que está sempre na sua playlist?",
    "Qual a melhor e mais memorável viagem que você já fez?",
    "Qual a última série que você maratonou?",
    "Qual o seu time? Qual?",
    "Qual a sua estação do ano preferida?",
    "Você prefere cozinhar ou pedir comida?",
    "No verão, você prefere praia ou piscina?",
    "Qual a pessoa da sua família mais próxima de você?",
    "Se você pudesse comer apenas uma comida pelo resto da sua vida, qual seria?",
    "Qual foi a primeira celebridade que você teve um crush?",
    "Você tem alguma citação preferida de livro, filme ou série? Qual é?",
    "O que te faz feliz durante o dia, independentemente do que você esteja fazendo?",
    "Qual o aplicativo de celular que você mais usa durante a semana?",
    "O que você faria se ganhasse na loteria hoje?",
    "Você tem algum amigo tão próximo que o considera parte da sua família?",
    "O que você mais tem orgulho sobre você?",
    "Qual a definição de sucesso para você?",
    "Quem é a pessoa que você mais admira no mundo?",
    "O que te deixou com mais orgulho de ter atingido nos últimos anos?",
    "Você preferiria ganhar menos dinheiro fazendo o que ama ou muito dinheiro fazendo o odeia?",
    "Gosta de baladas?",
    "Como você definiria o seu estilo?",
    "Tem algum ídolo?",
    "Qual a coisa mais estranha que já te falaram?",
    "Prefere receber ou dar elogios?",
    "Qual celebridade você levaria para uma ilha deserta?",
    "Como você acha que os seus pais definiriam você quando era criança?",
    "O que você mudaria em você se pudesse?",
    "Você gosta de dormir de conchinha?",
    "Qual a aventura mais extraordinária que já aconteceu na sua vida?",
    "Qual o toque do seu despertador?",
    "Qual foi o personagem infantil que mais te marcou na infância?",
    "Qual o seu jogo favorito?",
    "Você preferiria ter dinheiro infinito ou felicidade infinita?",
    "Você preferiria que alguém te machucasse, mas fosse honesto com você ou mentisse para proteger os seus sentimentos?",
    "Qual a coisa mais assustadora que você já fez na vida?",
    "Você é daquelas pessoas que dá uma segunda chance para alguém que te magoou?",
    "Você tem alguma fobia? Se sim, qual é?",
    "Você tem algum arrependimento na vida?",
    "Se você pudesse reviver um momento especial que marcou a sua vida, qual seria ele?",
    "Qual o momento ou período da história que você gostaria de ter vivido?",
    "Qual personagem fictício você mais se identifica e por quê?",
    "Qual a coisa mais estranha que você faz quando está sozinho?",
    "Você tem algum sonho recorrente?",
    "Qual a sua foto preferida no seu Instagram?",
    "Qual a sua foto preferida no meu Instagram?",
    "Se você pudesse mudar alguma coisa em você, o que seria?",
    "Como você demonstra amor a alguém?",
    "Qual foi o motivo do seu último término?",
    "O que você faz em momentos de estresse? Conversa com alguém ou prefere ficar um tempo sozinho?",
    "Você acredita em karma?",
    "O que te faz chorar com facilidade? E por quê?",
    "Você mantém amizade algum ex?",
    "Qual a sua opinião sobre relacionamentos abertos?",
    "Você se considera uma pessoa romântica?",
    "Já deixou de amar alguém por medo?",
    "Você dá muita importância para o que as pessoas pensam de você?",
    "O que geralmente as pessoas presumem sobre você que não é verdade?",
    "Você acredita que as pessoas podem realmente mudar quem elas são em seu interior?",
    "Como os seus amigos te descreveriam?",
    "Qual o seu hobbie preferido e como você se envolveu com ele pela primeira vez?",
    "O que você acha que é mais importante em uma amizade?",
    "Você é uma pessoa que se apaixona facilmente?",
    "Como você reage diante de uma rejeição?",
    "Você acha que quando iniciamos uma relação, perdemos um pouco da nossa liberdade?",
    "O que você mais gosta de ganhar como presente?",
    "Tem alguma coisa que você gostaria de experimentar, mas ainda não fez por medo?",
    "Existe alguma situação que a mentira é justificável para você?",
    "Você possui alguma insegurança?",
    "Qual a maior loucura de amor que você já fez?",
    "Existe alguma coisa que te faz sorrir, mesmo em dias tristes?",
    "Alguma recordação de infância que te faz mais feliz?",
    "Existe algum filme ou livro que te inspirou a tomar alguma decisão na vida?",
    "Poderia compartilhar algum aspecto que mais te agrada no seu melhor amigo ou amiga?",
    "O que você poderia fazer por 24 horas sem cansar?",
    "Qual a sua palavra preferida? Pode ser em qualquer idioma.",
    "Qual seria o encontro perfeito para você?",
    "Qual foi a primeira impressão que você teve de mim?",
    "Qual foi o motivo que te fez chorar pela última vez?",
    "Quando você era menor, qual era a profissão dos seus sonhos?",
    "Prefere pequenas reuniões entre amigos ou festas com muitas pessoas?",
    "Qual foi o ano mais desafiador e transformador da sua vida até agora?",
    "Qual o presente favorito que você ganhou quando criança?",
    "Qual a coisa mais bonita que alguém já disse sobre você?",
    "O que você gosta de fazer em uma tarde de chuva?",
    "Um objeto preferido que você tem no seu quarto?",
    "Qual a parte favorita do seu corpo?",
    "Qual a característica de personalidade que você mais detesta em alguém?",
    "Quando você sabe que está apaixonado?",
    "Como você descreveria o seu senso de humor?",
    "O que você faria se por um dia todas as leis fossem suspensas no mundo?",
    "Se você pudesse se transformar em um animal por um dia, qual seria?",
    "Que tipo de piada você acha que não tem nenhuma graça?",
    "Existe alguma música que reflete a sua personalidade?",
    "O nome de um filme que resumiria a sua vida?",
    "Você costuma se comparar com outras pessoas?",
    "Qual a coisa mais importante que sua mãe ou seu pai te ensinou?",
    "Qual a melhor memória que você possui de algum dos seus avós?",
    "Qual a sua opinião sobre o casamento?",
    "Você toca algum instrumento musical? Se sim, qual? Se não, gostaria de aprender algum?",
    "Qual show mais marcou a sua vida?",
    "Você se considera uma pessoa aventureira?",
    "Você preferiria ser 10 vezes mais inteligente ou 10 vezes mais feliz?",
    "Você possui algum hábito ou mania que gostaria de se livrar?",
    "Você preferiria morar em uma mansão no interior ou em um apartamento com uma vista espetacular da cidade?",
    "Qual seria o título da sua autobiografia?",
    "Se você pudesse dominar 100% um único talento, qual seria?",
    "Se algum dia se casar, onde gostaria que fosse a sua lua de mel?",
    "O que pensa sobre relacionamentos à distância?",
    "O que você prefere? Um abraço apertado por 10 minutos ou um beijo rápido por alguns segundos?",
    "Existe alguma música que faz você pensar em mim?",
    "O que significa amar para você?",
    "Seria capaz de perdoar uma traição?",
    "Você preferiria viajar para o futuro ou para o passado?",
    "Quantos filhos você gostaria de ter no futuro?",
    "Como você se descreveria em 3 adjetivos?",
    "Qual a sua maior motivação para acordar pela manhã?",
    "Qual o objeto mais precioso que você tem na sua casa?",
    "Qual o seu assunto preferido para conversar em uma mesa de bar?",
    "Se pudesse passar a vida inteira tendo a mesma idade, que idade seria?",
    "Qual a melhor pergunta que já fizeram sobre você ou que você gostaria que fizessem?",
    "Qual foi o seu relacionamento mais longo e o que você aprendeu com ele?",
    "Preferiria casar na praia ou em um cerimonial elegante?",
    "Qual o seu plano de vida a longo prazo?",
    "Você é uma pessoa mais produtiva durante a noite ou durante o dia?",
    "Você compartilharia um segredo comigo?",
    "Como você era na escola? Mais nerd ou da galera do fundão?",
    "Fale sobre 3 características que fazem uma relação ser perfeita.",
    "Qual o seu tipo de perfume preferido em outra pessoa?",
    "Quais são as 5 pessoas mais importantes e influentes na sua vida e por quê?",
    "O que você acha que te faz único neste mundo?",
    "O que você prefere? Sair para festas, sair para comer, ficar em casa vendo um filme ou ficar em casa lendo um livro?",
    "O que você faria se fosse invisível por um dia?",
    "O que você estaria disposto a fazer por 1 milhão de reais?",
    "Qual a sua opinião sobre religião e espiritualidade?",
    "Se pudesse ressuscitar algum famoso, quem seria e por quê?",
    "De 1 a 10. Quão importante é a aparência física para você?",
    "Você gostaria de ser imortal?",
    "Qual o sonho mais estranho ou peculiar que você já teve?",
    "Você sabe a história do seu nome ou porque os seus pais te batizaram com ele?",
    "Que música você detesta, mas sempre volta à sua memória?",
    "Qual o tipo de pessoa que mais te assusta neste mundo?",
    "Gostaria de ter treinado uma vocação desde pequeno?",
    "Você tem algum medo irracional?",
    "O que você mais sente saudade da sua infância?",
    "Reputação é algo importante para você?",
    "Qual a pior coisa que você já comprou ou já investiu?"
    ]
    resultado=random.choice(assuntos)
    return resultado    

    

def principal():
    while True:
        choice=input("O que você prefere,\n1- Piadas?\n2- Charadas?\n3- Assuntos?\n1, 2, 3:  ")
        if choice =='1':
            print(piadas_engraçadas(piadas=0))
        elif choice =='2':
            print(charadas_engraçadas(charadas=0))
        elif choice=='3':
            print(assuntos_gerador(assuntos=0))
        else:
            print("Escolha errada, escolha entre 1, 2 ou 3")
        resposta = input("Deseja constinuar?")
        if resposta.lower() != 'sim':
            print("Finalizando...")
            break
        
principal()